# services/db_schema.py
import sqlite3
from pathlib import Path
import pandas as pd
import json

class DatabaseManager:
    """
    Manages SQLite database interactions. 
    Enhanced with 'Rich Schema' and 'Safe Query' methods for LLM Context Awareness.
    """

    def __init__(self, db_path="data/aml_database.db"):
        self.db_path = db_path
        # Ensure directory exists immediately upon initialization
        try:
            Path(db_path).parent.mkdir(parents=True, exist_ok=True)
        except Exception as e:
            print(f"⚠️ Error creating DB directory: {e}")

    def connect(self, path=None):
        """
        Create a new database connection.
        Args:
            path (str, optional): If provided, connects to this specific DB file (e.g. inside a Case Environment).
                                  Otherwise, uses the default self.db_path.
        """
        target_path = path if path else self.db_path
        conn = sqlite3.connect(target_path, check_same_thread=False, timeout=30)
        conn.row_factory = sqlite3.Row # Allows accessing columns by name
        return conn

    def close_connection(self, conn):
        """Safely closes a database connection."""
        try:
            if conn:
                conn.close()
        except Exception:
            pass

    # ============================================================
    # LLM CONTEXT HELPERS (CRITICAL FOR CHAT ASSISTANT)
    # ============================================================
    
    def get_rich_schema(self, db_path=None):
        """
        Generates a detailed schema summary optimized for LLM understanding.
        Instead of just table names, it provides Column Names, Types, and a Sample Row.
        
        This allows the LLM to know that 'transaction_amount' is a number and 'customer_name' is text.
        """
        conn = self.connect(db_path)
        schema_summary = []
        
        try:
            cursor = conn.cursor()
            # 1. Get all user tables (exclude internal sqlite_ tables)
            cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'")
            tables = [r[0] for r in cursor.fetchall()]

            if not tables:
                return "Database is empty (no tables found)."

            for table in tables:
                # 2. Get column info (cid, name, type, notnull, dflt_value, pk)
                cursor.execute(f"PRAGMA table_info(\"{table}\")")
                columns = cursor.fetchall()
                
                # Format as: "col_name (TYPE)"
                col_defs = [f"{col['name']} ({col['type']})" for col in columns]
                schema_summary.append(f"Table '{table}':\n  Columns: {', '.join(col_defs)}")
                
                # 3. Fetch 1 sample row to give the LLM context on data formatting (e.g. Date format)
                try:
                    cursor.execute(f"SELECT * FROM \"{table}\" LIMIT 1")
                    sample = cursor.fetchone()
                    if sample:
                        sample_dict = dict(sample)
                        # Truncate very long values (like huge descriptions) to save token space
                        sample_str = str({k: (str(v)[:50] + '...') if len(str(v)) > 50 else v for k, v in sample_dict.items()})
                        schema_summary.append(f"  Sample Row: {sample_str}")
                except Exception as e:
                    pass # Ignore errors fetching samples
                
                schema_summary.append("") # Empty line separator

        except Exception as e:
            return f"Error reading schema: {str(e)}"
        finally:
            self.close_connection(conn)
            
        return "\n".join(schema_summary)

    def execute_safe_query(self, sql, db_path=None):
        """
        Executes a Read-Only SQL query generated by the LLM.
        Includes safeguards against destructive operations (DROP, DELETE).
        
        Returns:
            dict: { columns: [], data: [], row_count: int, truncated: bool }
        """
        # 1. Safety Block: Reject modification keywords to prevent data loss
        forbidden = ['DROP', 'DELETE', 'UPDATE', 'INSERT', 'ALTER', 'TRUNCATE', 'VACUUM', 'PRAGMA']
        if any(w in sql.upper() for w in forbidden):
            return {"error": "Safety Block: Modification queries (DROP, DELETE, UPDATE) are not allowed in Chat."}

        conn = self.connect(db_path)
        try:
            cursor = conn.cursor()
            cursor.execute(sql)
            
            # 2. Limit results to prevent blowing up the LLM context window
            # We fetch 50 rows max. If the user needs more, they should refine the query.
            rows = cursor.fetchmany(50) 
            
            if cursor.description:
                columns = [description[0] for description in cursor.description]
                result_data = [dict(zip(columns, row)) for row in rows]
            else:
                columns = []
                result_data = []
            
            return {
                "columns": columns,
                "row_count": len(result_data),
                "data": result_data,
                "truncated": len(result_data) == 50 # Flag to tell LLM there is more data
            }
        except Exception as e:
            return {"error": f"SQL Execution Failed: {str(e)}"}
        finally:
            self.close_connection(conn)

    # ============================================================
    # UI HELPERS (For Frontend Display)
    # ============================================================
    def get_display_tables(self):
        """Returns a list of tables meant for the UI, filtering out system/internal tables."""
        conn = self.connect()
        try:
            cursor = conn.cursor()
            cursor.execute("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name")
            all_tables = [r['name'] for r in cursor.fetchall()]
            
            # CLEANUP: Hide technical tables from the user
            hidden = ['sqlite_sequence', 'audit_log', 'alembic_version', 'system_master_registry', 'android_metadata']
            
            display_tables = [t for t in all_tables if t not in hidden and not t.startswith('idx_')]
            return display_tables
        except Exception as e:
            print(f"❌ Error listing tables: {e}")
            return []
        finally:
            self.close_connection(conn)

    # ============================================================
    # DYNAMIC SCHEMA MANAGEMENT (For File Uploads)
    # ============================================================
    def normalize_col_name(self, col_name):
        """Converts 'Customer ID' -> 'customer_id' to keep SQL sane."""
        if not col_name: return "col_unknown"
        return str(col_name).strip().lower().replace(' ', '_').replace('-', '_').replace('/', '_')

    def ensure_table_schema(self, table_name, df):
        """Dynamically creates table OR adds missing columns based on the DataFrame."""
        if df is None or df.empty: return df

        # Normalize DF columns to match DB style
        df.columns = [self.normalize_col_name(c) for c in df.columns]
        
        conn = self.connect()
        try:
            cursor = conn.cursor()
            cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name=?", (table_name,))
            table_exists = cursor.fetchone()

            if not table_exists:
                # --- Create New Table ---
                print(f"🆕 Creating dynamic table: '{table_name}'")
                csv_columns = set(df.columns)
                cols_defs = [f'"{col}" TEXT' for col in df.columns] 
                cols_sql = ", ".join(cols_defs)

                # Smartly add System Columns if they don't clash
                pk_sql = "id INTEGER PRIMARY KEY AUTOINCREMENT,"
                if 'id' in csv_columns: pk_sql = ""

                date_sql = ", created_at DATETIME DEFAULT CURRENT_TIMESTAMP"
                if 'created_at' in csv_columns: date_sql = ""

                create_sql = f"""CREATE TABLE "{table_name}" ({pk_sql} {cols_sql} {date_sql})"""
                cursor.execute(create_sql)
            else:
                # --- Update Existing Table ---
                cursor.execute(f"PRAGMA table_info(\"{table_name}\")")
                existing_cols = {row['name'] for row in cursor.fetchall()}
                new_cols = [col for col in df.columns if col not in existing_cols]

                if new_cols:
                    print(f"🔄 Evolving schema for '{table_name}'. Adding: {new_cols}")
                    for col in new_cols:
                        try:
                            cursor.execute(f'ALTER TABLE "{table_name}" ADD COLUMN "{col}" TEXT')
                        except Exception as e:
                            print(f"⚠️ Could not add column {col}: {e}")
            conn.commit()
            return df
        finally:
            self.close_connection(conn)

    # ============================================================
    # DATA INSERTION & UTILS
    # ============================================================
    def bulk_insert_table(self, table_name, df):
        """Inserts data into ANY table dynamically."""
        df_normalized = self.ensure_table_schema(table_name, df)
        if df_normalized is None or df_normalized.empty: return

        conn = self.connect()
        try:
            cursor = conn.cursor()
            columns = list(df_normalized.columns)
            cols_str = ", ".join([f'"{c}"' for c in columns])
            placeholders = ", ".join(["?"] * len(columns))
            
            sql = f'INSERT OR REPLACE INTO "{table_name}" ({cols_str}) VALUES ({placeholders})'
            data_to_insert = df_normalized.where(pd.notnull(df_normalized), None).values.tolist()
            cursor.executemany(sql, data_to_insert)
            conn.commit()
            print(f"✅ Inserted {len(data_to_insert)} rows into '{table_name}'")
        except Exception as e:
            print(f"❌ Insert Error in '{table_name}': {e}")
            raise e
        finally:
            self.close_connection(conn)

    def init_schema(self):
        """Creates strict system tables (Audit Log)."""
        conn = self.connect()
        cur = conn.cursor()
        cur.execute("""
        CREATE TABLE IF NOT EXISTS audit_log (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user TEXT, action TEXT, entity_type TEXT, 
            entity_id TEXT, details TEXT, 
            timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
        );
        """)
        conn.commit()
        self.close_connection(conn)