"""
workbench_routes.py  â€” Enhanced MLOps Workbench Backend Routes
Additions over the original:
  - File-level validation (extension, size cap, empty file guard)
  - Custom dataset type names â€” any bank can bring any table
  - Upload returns row_count, column list, column_types, file_path in response
  - GET /api/mlops/datasets  now returns richer metadata (column_types, file_path)
  - Multi-bank isolation via env_id/tenant_id (unchanged architecture, same path logic)
  - POST /api/mlops/upload/<dataset_type> now accepts 'custom' type via ?custom_name=
  - POST /api/mlops/datasets/<id>/delete  â€” soft-delete / re-upload workflow
  - All error responses now include machine-readable error_code for frontend handling
"""

from flask import Blueprint, request, jsonify
from pathlib import Path
import os
import re
import json
from datetime import datetime

from api.service_locator import services
from api.tools.mlops.mlops_workbench_service import MLOpsWorkbenchService
from api.tools.mlops.path_utils import resolve_env_root, resolve_mlops_data_dir


mlops_workbench_bp = Blueprint("mlops_workbench", __name__)

# â”€â”€â”€ Constants â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

ALLOWED_EXTENSIONS = {"csv", "parquet"}
MAX_FILE_BYTES     = 500 * 1024 * 1024          # 500 MB hard cap
CUSTOM_TYPE_RE     = re.compile(r"^[a-z0-9_\-]+$")   # safe type name pattern

# Pipeline artefacts â€” generated by the workbench, NEVER uploaded by users.
# These dataset_types are produced internally (master build, preprocessing, etc.)
# Uploading them directly would corrupt the pipeline state.
PIPELINE_ARTEFACT_TYPES = frozenset({
    "master_dataset", "master",
    "preprocessed_dataset", "preprocessed",
    "model_output", "model_dataset", "scored_dataset", "feature_store",
})

# Raw operational file types the user is allowed to upload
ALLOWED_UPLOAD_TYPES = frozenset({
    "transactions", "accounts", "customers", "alerts", "cases",
    "str", "sar", "sanctions", "watchlist", "custom",
})

# â”€â”€â”€ Helpers â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

def _resolve_env_path(env_id: str, tenant_id: str) -> str:
    return str(resolve_env_root(env_id, tenant_id, create_if_missing=True))


def _get_env_ids():
    env_id = (
        request.args.get("env_id")
        or request.headers.get("X-Environment-ID")
        or services.metadata_manager.active_env
    )
    if not env_id:
        raise ValueError("X-Environment-ID header required")
    tenant_id = request.tenant_id
    return tenant_id, env_id


_BUSINESS_GOAL_LABELS = {
    "catch_most": "Catch as many real cases as possible",
    "balanced": "Balance detection with analyst workload",
    "minimize_false_alarms": "Reduce false alarms first",
}


def _stringify_business_signal(signal) -> str:
    if isinstance(signal, str):
        return signal.strip()
    if isinstance(signal, dict):
        title = str(
            signal.get("title")
            or signal.get("label")
            or signal.get("name")
            or ""
        ).strip()
        detail = str(
            signal.get("detail")
            or signal.get("summary")
            or signal.get("value")
            or signal.get("message")
            or ""
        ).strip()
        if title and detail:
            return f"{title}: {detail}"
        return title or detail
    return str(signal or "").strip()


def _extract_llm_json(raw_text: str):
    text = str(raw_text or "").strip()
    if not text:
        return None
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if match:
        text = match.group(0)
    try:
        return json.loads(text)
    except Exception:
        return None


def _build_business_brief_payload(profile_rows, target_column: str, goal: str) -> dict:
    dataset_cards = []
    total_rows = 0
    total_entities = 0
    coverage_values = []
    freshness_values = []
    flag_rates = []
    standout_signals = []

    for row in profile_rows:
        dataset = row["dataset"]
        profile = row["profile"] or {}
        row_count = int(profile.get("total_rows") or dataset.get("row_count") or 0)
        quality_score = profile.get("quality_score")
        coverage_pct = profile.get("coverage_pct")
        freshness_days = profile.get("data_freshness_days")
        unique_entities = int(profile.get("unique_entity_count") or 0)
        flag_rate = profile.get("flag_rate")
        signals = [
            text
            for text in (
                _stringify_business_signal(signal)
                for signal in (profile.get("business_signals") or [])
            )
            if text
        ]

        total_rows += row_count
        total_entities += unique_entities
        if coverage_pct is not None:
            coverage_values.append(float(coverage_pct))
        if freshness_days is not None:
            freshness_values.append(int(freshness_days))
        if flag_rate is not None:
            flag_rates.append(float(flag_rate))
        standout_signals.extend(signals[:3])

        dataset_cards.append(
            {
                "dataset_id": int(dataset.get("dataset_id") or 0),
                "dataset_type": str(dataset.get("dataset_type") or "dataset"),
                "rows": row_count,
                "quality_score": float(quality_score) if quality_score is not None else None,
                "business_narrative": str(profile.get("business_narrative") or "No summary available."),
                "coverage_pct": float(coverage_pct) if coverage_pct is not None else None,
                "data_freshness_days": int(freshness_days) if freshness_days is not None else None,
                "unique_entity_count": unique_entities or None,
                "flag_rate": float(flag_rate) if flag_rate is not None else None,
                "signals": signals[:4],
            }
        )

    unique_signals = []
    seen_signals = set()
    for signal in standout_signals:
        normalized = signal.lower()
        if normalized in seen_signals:
            continue
        seen_signals.add(normalized)
        unique_signals.append(signal)
        if len(unique_signals) >= 4:
            break

    avg_coverage = round(sum(coverage_values) / len(coverage_values), 2) if coverage_values else None
    freshest_data_days = min(freshness_values) if freshness_values else None
    avg_flag_rate = round(sum(flag_rates) / len(flag_rates), 4) if flag_rates else None
    goal_label = _BUSINESS_GOAL_LABELS.get(goal, _BUSINESS_GOAL_LABELS["balanced"])

    summary_bits = [
        f"{len(dataset_cards)} data source{'s' if len(dataset_cards) != 1 else ''}",
        f"{total_rows:,} total rows" if total_rows else "",
        f"{total_entities:,} tracked entities" if total_entities else "",
        f"about {avg_flag_rate * 100:.1f}% currently flagged" if avg_flag_rate is not None else "",
    ]
    summary_bits = [bit for bit in summary_bits if bit]
    executive_summary = (
        "You selected "
        + ", ".join(summary_bits)
        + f". The current operating priority is to {goal_label.lower()}."
    )
    if target_column:
        executive_summary += f" The chosen outcome column is {target_column}."
    if freshest_data_days is not None:
        executive_summary += f" The freshest sampled data is {freshest_data_days} days old."

    recommended_actions = []
    if not target_column:
        recommended_actions.append("Confirm which business outcome column represents success before starting the build.")
    if avg_coverage is not None and avg_coverage < 80:
        recommended_actions.append("Review key coverage before trusting the automated build because sparse IDs weaken joins.")
    if len(dataset_cards) < 2:
        recommended_actions.append("Add more supporting data sources if you want a fuller picture than a single table can provide.")
    if goal == "catch_most":
        recommended_actions.append("Prepare the investigation team for a higher review queue because this priority favors coverage.")
    elif goal == "minimize_false_alarms":
        recommended_actions.append("Validate missed-case tolerance with compliance stakeholders because this priority favors efficiency.")
    else:
        recommended_actions.append("Start with the balanced operating mode if you want a credible first pass for business review.")
    recommended_actions = recommended_actions[:4]

    questions_to_answer = [
        "Which business outcome matters most: finding more real cases or reducing analyst workload?",
        "Is the selected outcome column trusted by operations and compliance teams?",
        "Are there any important data sources still missing from this build?",
    ]

    return {
        "llm_available": False,
        "brief_source": "deterministic",
        "goal": goal,
        "goal_label": goal_label,
        "target_column": target_column or "",
        "executive_summary": executive_summary,
        "what_stands_out": unique_signals or ["No major structural risk signals were detected in the selected sample."],
        "recommended_actions": recommended_actions,
        "questions_to_answer": questions_to_answer,
        "combined_snapshot": {
            "dataset_count": len(dataset_cards),
            "total_rows": total_rows,
            "total_entities": total_entities or None,
            "avg_coverage_pct": avg_coverage,
            "avg_flag_rate": avg_flag_rate,
            "freshest_data_days": freshest_data_days,
        },
        "datasets": dataset_cards,
    }


def _maybe_upgrade_brief_with_llm(brief_payload: dict) -> dict:
    wrapper = getattr(services, "llm_provider", None) or getattr(services, "ollama_wrapper", None)
    if not wrapper:
        return brief_payload
    try:
        if not wrapper.check_connection():
            return brief_payload
    except Exception:
        return brief_payload

    prompt_payload = {
        "goal_label": brief_payload.get("goal_label"),
        "target_column": brief_payload.get("target_column"),
        "combined_snapshot": brief_payload.get("combined_snapshot"),
        "datasets": [
            {
                "dataset_type": row.get("dataset_type"),
                "rows": row.get("rows"),
                "quality_score": row.get("quality_score"),
                "business_narrative": row.get("business_narrative"),
                "signals": row.get("signals"),
            }
            for row in (brief_payload.get("datasets") or [])
        ],
        "what_stands_out": brief_payload.get("what_stands_out") or [],
    }
    system_prompt = (
        "You translate FCC and AML workbench facts into plain business language. "
        "Use short sentences. Do not use em dashes. Do not invent facts. "
        "Return valid JSON with keys executive_summary, what_stands_out, "
        "recommended_actions, questions_to_answer. Each list should contain 2 to 4 short strings."
    )
    response = wrapper.generate(
        prompt=json.dumps(prompt_payload, default=str),
        system_prompt=system_prompt,
        temperature=0.2,
        max_tokens=400,
    )
    if not response or not response.get("success"):
        return brief_payload

    parsed = _extract_llm_json(response.get("response", ""))
    if not isinstance(parsed, dict):
        return brief_payload

    upgraded = dict(brief_payload)
    upgraded["llm_available"] = True
    upgraded["brief_source"] = "ai"
    upgraded["ai_model"] = response.get("model")

    summary = str(parsed.get("executive_summary") or "").strip()
    if summary:
        upgraded["executive_summary"] = summary

    for key in ("what_stands_out", "recommended_actions", "questions_to_answer"):
        values = parsed.get(key)
        if isinstance(values, list):
            cleaned = [str(item).strip() for item in values if str(item).strip()]
            if cleaned:
                upgraded[key] = cleaned[:4]

    return upgraded


def _safe_dataset_type(raw: str) -> str:
    """Validate and normalise a dataset type string."""
    t = str(raw or "").strip().lower()
    if not t:
        raise ValueError("dataset_type is required")
    if not CUSTOM_TYPE_RE.match(t):
        raise ValueError(
            "dataset_type must contain only lowercase letters, digits, underscores, or hyphens"
        )
    if len(t) > 64:
        raise ValueError("dataset_type must be 64 characters or fewer")
    return t


def _get_mlops_service(env_root: str) -> MLOpsWorkbenchService:
    mlops_db = Path(env_root) / "mlops" / "duckdb" / "mlops.duckdb"
    return MLOpsWorkbenchService(mlops_db)


def _json_safe(value):
    """
    Convert non-JSON-native values (e.g., pandas NaT/Timestamp) into
    a structure that Flask can always jsonify.
    """
    return json.loads(json.dumps(value, default=str))


def _validate_upload_file(file) -> dict | None:
    """
    Returns None when valid, or a dict with {error, error_code} when invalid.
    """
    if not file or file.filename == "":
        return {"error": "No file provided or empty filename.", "error_code": "NO_FILE"}

    ext = file.filename.rsplit(".", 1)[-1].lower() if "." in file.filename else ""
    if ext not in ALLOWED_EXTENSIONS:
        return {
            "error": f"File type '.{ext}' is not supported. Please upload a CSV or Parquet file.",
            "error_code": "INVALID_EXTENSION",
        }

    # Check file size â€” seek to end to get byte length
    file.stream.seek(0, 2)
    size_bytes = file.stream.tell()
    file.stream.seek(0)

    if size_bytes == 0:
        return {"error": "The uploaded file is empty.", "error_code": "EMPTY_FILE"}

    if size_bytes > MAX_FILE_BYTES:
        mb = size_bytes / (1024 ** 2)
        return {
            "error": f"File is {mb:.0f} MB â€” the maximum allowed size is 500 MB.",
            "error_code": "FILE_TOO_LARGE",
        }

    return None


def _as_bool(raw) -> bool:
    return str(raw or "").strip().lower() in {"1", "true", "yes", "on"}


# â”€â”€â”€ Upload â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

@mlops_workbench_bp.route("/upload/<dataset_type>", methods=["POST"])
def mlops_upload_dataset(dataset_type):
    """
    POST /api/mlops/upload/<dataset_type>
    Upload a CSV or Parquet file and register it in the MLOps dataset registry.

    Special case: if dataset_type == 'custom', the actual type name must be
    supplied as a query param: ?custom_name=wire_transfers
    (or as a JSON body field 'custom_name')

    Returns:
      { success, data: { dataset_id, dataset_type, row_count, columns, column_types, file_path } }
    """
    try:
        # Resolve the effective dataset type
        raw_type = str(dataset_type or "").strip().lower()
        if raw_type == "custom":
            custom_name = (
                request.args.get("custom_name")
                or (request.form.get("custom_name") if request.form else None)
            )
            if not custom_name:
                return jsonify({
                    "success": False,
                    "error": "custom_name query parameter is required when dataset_type is 'custom'.",
                    "error_code": "MISSING_CUSTOM_NAME",
                }), 400
            raw_type = custom_name

        effective_type = _safe_dataset_type(raw_type)

        # Block pipeline artefact types
        if effective_type in PIPELINE_ARTEFACT_TYPES:
            return jsonify({
                "success": False,
                "error": (
                    f"'{effective_type}' is a pipeline artefact generated automatically by the workbench. "
                    "You cannot upload it directly. "
                    "Please upload only raw operational files: transactions, accounts, customers, alerts, cases, or str."
                ),
                "error_code": "ARTEFACT_TYPE_REJECTED",
            }), 400

        if "file" not in request.files:
            return jsonify({
                "success": False,
                "error": "No file part in request.",
                "error_code": "NO_FILE",
            }), 400

        file = request.files["file"]
        file_error = _validate_upload_file(file)
        if file_error:
            return jsonify({"success": False, **file_error}), 400

        tenant_id, env_id = _get_env_ids()
        env_root = _resolve_env_path(env_id, tenant_id)
        data_dir = resolve_mlops_data_dir(env_root, create_if_missing=True)

        ext = Path(file.filename).suffix.lower()
        save_path = data_dir / f"{effective_type}{ext}"
        file.save(str(save_path))

        # Cross-module ingestion is disabled. MLOps uploads stay in the MLOps workspace only.
        persist_requested = _as_bool(
            request.args.get("persist_to_main_db")
            or (request.form.get("persist_to_main_db") if request.form else None)
        )
        isolation_warning = None
        if persist_requested:
            isolation_warning = (
                "persist_to_main_db is disabled for MLOps uploads. "
                "The dataset was kept inside the isolated MLOps workspace."
            )

        mlops_svc = _get_mlops_service(env_root)
        dataset = mlops_svc.register_dataset(
            tenant_id=tenant_id,
            env_id=env_id,
            dataset_type=effective_type,
            filename=f"{effective_type}{ext}",
            file_path=save_path,
        )

        response_payload = {
            "success": True,
            "data": {
                "dataset_id": dataset["dataset_id"],
                "dataset_type": dataset["dataset_type"],
                "filename": dataset["filename"],
                "file_path": dataset["file_path"],
                "row_count": dataset["row_count"],
                "columns": dataset["columns"],
                "column_types": dataset["column_types"],
                "persisted_to_main_db": False,
            },
        }
        if isolation_warning:
            response_payload["warning"] = isolation_warning

        return jsonify(response_payload), 200

    except ValueError as ve:
        return jsonify({"success": False, "error": str(ve), "error_code": "VALIDATION_ERROR"}), 400
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500

# â”€â”€â”€ Dataset List â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

@mlops_workbench_bp.route("/datasets", methods=["GET"])
def mlops_list_datasets():
    """
    GET /api/mlops/datasets
    List all datasets registered for the current environment.

    Query params:
      - sync=1|true|force  -> rescan mlops/data/ and register discovered files
      - sync=force         -> rescan and recompute metadata for existing files too

    Default behavior is fast list-only (no heavy file scan), which keeps startup
    responsive while still preserving explicit sync when needed.
    """
    try:
        tenant_id, env_id = _get_env_ids()
        env_root = _resolve_env_path(env_id, tenant_id)
        mlops_svc = _get_mlops_service(env_root)

        sync_param = str(request.args.get("sync") or "").strip().lower()
        do_sync = sync_param in {"1", "true", "yes", "on", "force", "full"}
        force_sync = sync_param in {"force", "full"}
        synced = []

        if do_sync:
            data_dir = resolve_mlops_data_dir(env_root, create_if_missing=False)
            if data_dir.exists():
                synced = mlops_svc.sync_from_directory(
                    tenant_id=tenant_id,
                    env_id=env_id,
                    data_dir=data_dir,
                    force=force_sync,
                )

        datasets = mlops_svc.list_datasets(tenant_id, env_id)

        # â”€â”€ Split into raw uploads vs pipeline artefacts â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
        # The frontend Upload screen shows only raw_datasets.
        # Pipeline artefacts (master, preprocessed) are surfaced in the context panel.
        raw_datasets       = [d for d in datasets if d.get("dataset_type") not in PIPELINE_ARTEFACT_TYPES]
        artefact_datasets  = [d for d in datasets if d.get("dataset_type") in PIPELINE_ARTEFACT_TYPES]

        return jsonify({
            "success":    True,
            "data":       datasets,            # full list for backward-compat
            "raw":        raw_datasets,        # only user-uploaded tables
            "artefacts":  artefact_datasets,   # workbench-generated artefacts
            "sync_applied": bool(do_sync),
            "sync_mode": "force" if force_sync else ("incremental" if do_sync else "none"),
            "sync_count": int(len(synced)),
        }), 200

    except ValueError as ve:
        return jsonify({"success": False, "error": str(ve), "error_code": "VALIDATION_ERROR"}), 400
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


# â”€â”€â”€ Dataset Detail â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

@mlops_workbench_bp.route("/datasets/<int:dataset_id>", methods=["GET"])
def mlops_get_dataset(dataset_id):
    """GET /api/mlops/datasets/<id>"""
    try:
        tenant_id, env_id = _get_env_ids()
        env_root  = _resolve_env_path(env_id, tenant_id)
        mlops_svc = _get_mlops_service(env_root)
        dataset   = mlops_svc.get_dataset(tenant_id, env_id, dataset_id)
        if not dataset:
            return jsonify({"success": False, "error": "Dataset not found.", "error_code": "NOT_FOUND"}), 404
        return jsonify({"success": True, "data": dataset}), 200
    except ValueError as ve:
        return jsonify({"success": False, "error": str(ve), "error_code": "VALIDATION_ERROR"}), 400
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


# â”€â”€â”€ Dataset Soft-Delete â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

@mlops_workbench_bp.route("/datasets/<int:dataset_id>/delete", methods=["POST"])
def mlops_delete_dataset(dataset_id):
    """
    POST /api/mlops/datasets/<id>/delete
    Remove a dataset from the registry (file is kept on disk for audit).
    Useful when a bank wants to re-upload with corrected data.
    """
    try:
        tenant_id, env_id = _get_env_ids()
        env_root  = _resolve_env_path(env_id, tenant_id)
        mlops_svc = _get_mlops_service(env_root)
        mlops_svc.delete_dataset(tenant_id, env_id, dataset_id)
        return jsonify({"success": True, "message": "Dataset removed from registry."}), 200
    except ValueError as ve:
        return jsonify({"success": False, "error": str(ve), "error_code": "VALIDATION_ERROR"}), 400
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


@mlops_workbench_bp.route("/datasets/<int:dataset_id>/profile", methods=["GET"])
def mlops_dataset_profile(dataset_id):
    """
    GET /api/mlops/datasets/<id>/profile

    Return the cached auto-profile computed at upload time.
    Returns null if profiling is still in progress (non-blocking).
    """
    try:
        tenant_id, env_id = _get_env_ids()
        env_root  = _resolve_env_path(env_id, tenant_id)
        mlops_svc = _get_mlops_service(env_root)
        profile   = mlops_svc.get_dataset_profile(dataset_id)
        return jsonify({"success": True, "data": profile}), 200
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


@mlops_workbench_bp.route("/datasets/<int:dataset_id>/rows", methods=["GET"])
def mlops_dataset_rows_preview(dataset_id):
    """
    GET /api/mlops/datasets/<id>/rows

    Query params:
      - sample_rows: int (default 12, max 200)
      - columns: comma-separated column list (optional)
      - aggregate: 1|true|yes|on (optional)
      - aggregate_by: join key hint, e.g. account_id (optional)
    """
    try:
        tenant_id, env_id = _get_env_ids()
        env_root = _resolve_env_path(env_id, tenant_id)
        mlops_svc = _get_mlops_service(env_root)
        dataset = mlops_svc.get_dataset(tenant_id, env_id, dataset_id)
        if not dataset:
            return jsonify({"success": False, "error": "Dataset not found.", "error_code": "NOT_FOUND"}), 404

        sample_rows = int(request.args.get("sample_rows") or 12)
        columns_raw = str(request.args.get("columns") or "")
        columns = [c.strip() for c in columns_raw.split(",") if c.strip()] if columns_raw else None
        aggregate_flag = str(request.args.get("aggregate") or "").strip().lower()
        include_aggregation = aggregate_flag in {"1", "true", "yes", "on"}
        aggregate_by = request.args.get("aggregate_by") or None

        preview = mlops_svc.preview_dataset_rows(
            dataset=dataset,
            sample_rows=sample_rows,
            columns=columns,
            include_aggregation=include_aggregation,
            aggregate_by=aggregate_by,
        )
        return jsonify({"success": True, "data": _json_safe(preview)}), 200
    except ValueError as ve:
        return jsonify({"success": False, "error": str(ve), "error_code": "VALIDATION_ERROR"}), 400
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500



@mlops_workbench_bp.route("/datasets/reset", methods=["POST", "GET", "PUT", "OPTIONS"])
def mlops_reset_datasets():
    """
    POST /api/mlops/datasets/reset
    Reset pipeline state for the active env.
    Body:
      { delete_files: false }  # optional, default false
    """
    try:
        if request.method == "OPTIONS":
            return jsonify({"success": True, "data": {"ok": True}}), 200
        if request.method == "GET":
            delete_files_raw = str(request.args.get("delete_files") or "").strip().lower()
            delete_files = delete_files_raw in {"1", "true", "yes", "on"}
        else:
            body = request.get_json(silent=True) or {}
            delete_files = bool(body.get("delete_files", False))
        tenant_id, env_id = _get_env_ids()
        env_root = _resolve_env_path(env_id, tenant_id)
        mlops_svc = _get_mlops_service(env_root)
        result = mlops_svc.reset_workspace(tenant_id, env_id, delete_files=delete_files)
        return jsonify({"success": True, "data": result}), 200
    except ValueError as ve:
        return jsonify({"success": False, "error": str(ve), "error_code": "VALIDATION_ERROR"}), 400
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


# â”€â”€â”€ Metadata / Profile â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

@mlops_workbench_bp.route("/metadata/profile", methods=["POST"])
def mlops_metadata_profile():
    """POST /api/mlops/metadata/profile"""
    try:
        body       = request.get_json(silent=True) or {}
        dataset_id = int(body.get("dataset_id") or 0)
        sample     = int(body.get("sample_rows") or 5000)
        tenant_id, env_id = _get_env_ids()
        env_root   = _resolve_env_path(env_id, tenant_id)
        mlops_svc  = _get_mlops_service(env_root)
        dataset    = mlops_svc.get_dataset(tenant_id, env_id, dataset_id)
        if not dataset:
            return jsonify({"success": False, "error": "Dataset not found.", "error_code": "NOT_FOUND"}), 404
        result = mlops_svc.profile_metadata(dataset, sample)
        return jsonify({"success": True, "data": result}), 200
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


@mlops_workbench_bp.route("/business/brief", methods=["POST"])
def mlops_business_brief():
    """POST /api/mlops/business/brief"""
    try:
        body = request.get_json(silent=True) or {}
        dataset_ids = body.get("dataset_ids") or []
        sample_rows = max(500, min(int(body.get("sample_rows") or 4000), 15000))
        target_column = str(body.get("target_column") or "").strip()
        goal = str(body.get("goal") or "balanced").strip().lower() or "balanced"

        tenant_id, env_id = _get_env_ids()
        env_root = _resolve_env_path(env_id, tenant_id)
        mlops_svc = _get_mlops_service(env_root)

        profile_rows = []
        for raw_dataset_id in dataset_ids:
            try:
                dataset_id = int(raw_dataset_id)
            except Exception:
                continue
            dataset = mlops_svc.get_dataset(tenant_id, env_id, dataset_id)
            if not dataset:
                continue
            profile_rows.append(
                {
                    "dataset": dataset,
                    "profile": mlops_svc.profile_metadata(dataset, sample_rows),
                }
            )

        if not profile_rows:
            return jsonify({
                "success": False,
                "error": "At least one valid dataset is required.",
                "error_code": "VALIDATION_ERROR",
            }), 400

        brief = _build_business_brief_payload(profile_rows, target_column, goal)
        brief = _maybe_upgrade_brief_with_llm(brief)
        return jsonify({"success": True, "data": brief}), 200
    except ValueError as ve:
        return jsonify({"success": False, "error": str(ve), "error_code": "VALIDATION_ERROR"}), 400
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


@mlops_workbench_bp.route("/metadata/schema-preview", methods=["POST"])
def mlops_schema_preview():
    """POST /api/mlops/metadata/schema-preview"""
    try:
        body       = request.get_json(silent=True) or {}
        dataset_id = int(body.get("dataset_id") or 0)
        limit      = int(body.get("limit") or 25)
        tenant_id, env_id = _get_env_ids()
        env_root   = _resolve_env_path(env_id, tenant_id)
        mlops_svc  = _get_mlops_service(env_root)
        dataset    = mlops_svc.get_dataset(tenant_id, env_id, dataset_id)
        if not dataset:
            return jsonify({"success": False, "error": "Dataset not found.", "error_code": "NOT_FOUND"}), 404
        result = mlops_svc.schema_preview(dataset, limit=limit)
        return jsonify({"success": True, "data": result}), 200
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


@mlops_workbench_bp.route("/metadata/join-graph", methods=["POST"])
def mlops_join_graph():
    """POST /api/mlops/metadata/join-graph"""
    try:
        body        = request.get_json(silent=True) or {}
        dataset_ids = body.get("dataset_ids") or []
        sample      = int(body.get("sample_rows") or 5000)
        tenant_id, env_id = _get_env_ids()
        env_root   = _resolve_env_path(env_id, tenant_id)
        mlops_svc  = _get_mlops_service(env_root)
        datasets   = [
            mlops_svc.get_dataset(tenant_id, env_id, int(did))
            for did in dataset_ids
            if did
        ]
        datasets = [d for d in datasets if d]
        result   = mlops_svc.join_relationships(datasets, sample_rows=sample)
        return jsonify({"success": True, "data": result}), 200
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


# â”€â”€â”€ Target & STR â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

@mlops_workbench_bp.route("/target/derive", methods=["POST"])
def mlops_derive_target():
    """POST /api/mlops/target/derive"""
    try:
        body       = request.get_json(silent=True) or {}
        dataset_id = int(body.get("dataset_id") or 0)
        strategy   = body.get("strategy")
        config     = dict(body.get("config") or {})

        # Frontend compatibility:
        # Step 3 sends {dataset_id, column}. Promote it to config.flag_column
        # and use an explicit "existing" strategy.
        direct_col = (
            body.get("column")
            or body.get("target_column")
            or config.get("column")
            or config.get("target_column")
            or config.get("flag_column")
        )
        if direct_col:
            config["flag_column"] = str(direct_col).strip()
            if not strategy:
                strategy = "existing"

        strategy = strategy or "case_outcome"

        if not dataset_id:
            return jsonify({
                "success": False,
                "error": "dataset_id is required",
                "error_code": "VALIDATION_ERROR",
            }), 400

        tenant_id, env_id = _get_env_ids()
        env_root   = _resolve_env_path(env_id, tenant_id)
        mlops_svc  = _get_mlops_service(env_root)
        dataset    = mlops_svc.get_dataset(tenant_id, env_id, dataset_id)
        if not dataset:
            return jsonify({"success": False, "error": "Dataset not found.", "error_code": "NOT_FOUND"}), 404
        result = mlops_svc.derive_target(tenant_id, env_id, dataset, strategy, config)
        return jsonify({"success": True, "data": result}), 200
    except ValueError as ve:
        return jsonify({"success": False, "error": str(ve), "error_code": "VALIDATION_ERROR"}), 400
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


@mlops_workbench_bp.route("/target/generate-str", methods=["POST"])
def mlops_generate_str():
    """POST /api/mlops/target/generate-str"""
    # Delegate to the target blueprint implementation so both legacy and
    # canonical endpoints use the same CASE_STATUS/STR derivation logic.
    from .target_routes import generate_str_target

    return generate_str_target()


@mlops_workbench_bp.route("/target/str-rules", methods=["POST"])
def mlops_save_str_rules():
    """POST /api/mlops/target/str-rules"""
    try:
        body      = request.get_json(silent=True) or {}
        rules     = body.get("rules") or []
        tenant_id, env_id = _get_env_ids()
        env_root  = _resolve_env_path(env_id, tenant_id)
        mlops_svc = _get_mlops_service(env_root)
        mlops_svc.save_str_rules(tenant_id, env_id, rules)
        return jsonify({"success": True}), 200
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


# â”€â”€â”€ EDA Core â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

def _require_dataset(mlops_svc, tenant_id, env_id, body):
    dataset_id = int(body.get("dataset_id") or 0)
    dataset    = mlops_svc.get_dataset(tenant_id, env_id, dataset_id)
    if not dataset:
        raise ValueError("Dataset not found")
    return dataset


@mlops_workbench_bp.route("/variables/stats", methods=["POST"])
def mlops_variable_stats():
    try:
        body = request.get_json(silent=True) or {}
        tenant_id, env_id = _get_env_ids()
        env_root   = _resolve_env_path(env_id, tenant_id)
        mlops_svc  = _get_mlops_service(env_root)
        dataset    = _require_dataset(mlops_svc, tenant_id, env_id, body)
        result     = mlops_svc.variable_stats(dataset, int(body.get("sample_rows") or 5000))
        return jsonify({"success": True, "data": result}), 200
    except ValueError as ve:
        return jsonify({"success": False, "error": str(ve), "error_code": "NOT_FOUND"}), 404
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


@mlops_workbench_bp.route("/correlation", methods=["POST"])
def mlops_correlation():
    try:
        body = request.get_json(silent=True) or {}
        tenant_id, env_id = _get_env_ids()
        env_root   = _resolve_env_path(env_id, tenant_id)
        mlops_svc  = _get_mlops_service(env_root)
        dataset    = _require_dataset(mlops_svc, tenant_id, env_id, body)
        async_mode = bool(body.get("async"))
        if async_mode:
            job_id = mlops_svc.submit_job(
                "correlation", {"dataset_id": dataset["dataset_id"],
                                "columns": body.get("columns"),
                                "sample_rows": int(body.get("sample_rows") or 8000),
                                "method": body.get("method") or "pearson"}
            )
            return jsonify({"job_id": job_id}), 202
        result = mlops_svc.correlation(
            dataset, body.get("columns"), int(body.get("sample_rows") or 8000),
            body.get("method") or "pearson"
        )
        return jsonify({"success": True, "data": result}), 200
    except ValueError as ve:
        return jsonify({"success": False, "error": str(ve), "error_code": "NOT_FOUND"}), 404
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


@mlops_workbench_bp.route("/outliers", methods=["POST"])
def mlops_outliers():
    try:
        body = request.get_json(silent=True) or {}
        tenant_id, env_id = _get_env_ids()
        env_root   = _resolve_env_path(env_id, tenant_id)
        mlops_svc  = _get_mlops_service(env_root)
        dataset    = _require_dataset(mlops_svc, tenant_id, env_id, body)
        columns    = body.get("columns") if body.get("columns") is not None else body.get("column")
        result     = mlops_svc.outliers(
            dataset, columns,
            int(body.get("sample_rows") or 5000),
            body.get("method") or "iqr",
            float(body.get("threshold") or 1.5),
        )
        return jsonify({"success": True, "data": result}), 200
    except ValueError as ve:
        return jsonify({"success": False, "error": str(ve), "error_code": "NOT_FOUND"}), 404
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


@mlops_workbench_bp.route("/duplicates", methods=["POST"])
def mlops_duplicates():
    try:
        body = request.get_json(silent=True) or {}
        tenant_id, env_id = _get_env_ids()
        env_root   = _resolve_env_path(env_id, tenant_id)
        mlops_svc  = _get_mlops_service(env_root)
        dataset    = _require_dataset(mlops_svc, tenant_id, env_id, body)
        result     = mlops_svc.duplicates(dataset, int(body.get("sample_rows") or 8000))
        return jsonify({"success": True, "data": result}), 200
    except ValueError as ve:
        return jsonify({"success": False, "error": str(ve), "error_code": "NOT_FOUND"}), 404
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


@mlops_workbench_bp.route("/insights", methods=["POST"])
def mlops_insights():
    try:
        body = request.get_json(silent=True) or {}
        tenant_id, env_id = _get_env_ids()
        env_root   = _resolve_env_path(env_id, tenant_id)
        mlops_svc  = _get_mlops_service(env_root)
        dataset    = _require_dataset(mlops_svc, tenant_id, env_id, body)
        async_mode = bool(body.get("async"))
        if async_mode:
            job_id = mlops_svc.submit_job(
                "insights", {"dataset_id": dataset["dataset_id"],
                             "sample_rows": int(body.get("sample_rows") or 8000)}
            )
            return jsonify({"job_id": job_id}), 202
        result = mlops_svc.insights(dataset, int(body.get("sample_rows") or 8000))
        return jsonify({"success": True, "data": result}), 200
    except ValueError as ve:
        return jsonify({"success": False, "error": str(ve), "error_code": "NOT_FOUND"}), 404
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


# â”€â”€â”€ EDA Advanced â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

@mlops_workbench_bp.route("/eda/column-profile", methods=["POST"])
def mlops_column_profile():
    try:
        body = request.get_json(silent=True) or {}
        tenant_id, env_id = _get_env_ids()
        env_root   = _resolve_env_path(env_id, tenant_id)
        mlops_svc  = _get_mlops_service(env_root)
        dataset    = _require_dataset(mlops_svc, tenant_id, env_id, body)
        result     = mlops_svc.column_profile(
            dataset, body.get("columns"),
            int(body.get("sample_rows") or 5000),
            int(body.get("bins") or 20),
        )
        return jsonify({"success": True, "data": result}), 200
    except ValueError as ve:
        return jsonify({"success": False, "error": str(ve), "error_code": "NOT_FOUND"}), 404
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


@mlops_workbench_bp.route("/eda/quality-score", methods=["POST"])
def mlops_quality_score():
    try:
        body = request.get_json(silent=True) or {}
        tenant_id, env_id = _get_env_ids()
        env_root   = _resolve_env_path(env_id, tenant_id)
        mlops_svc  = _get_mlops_service(env_root)
        dataset    = _require_dataset(mlops_svc, tenant_id, env_id, body)
        result     = mlops_svc.quality_score(
            dataset,
            body.get("target_column") or "",
            int(body.get("sample_rows") or 5000),
        )
        return jsonify({"success": True, "data": result}), 200
    except ValueError as ve:
        return jsonify({"success": False, "error": str(ve), "error_code": "NOT_FOUND"}), 404
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


@mlops_workbench_bp.route("/eda/feature-target", methods=["POST"])
def mlops_feature_target():
    try:
        body = request.get_json(silent=True) or {}
        tenant_id, env_id = _get_env_ids()
        env_root   = _resolve_env_path(env_id, tenant_id)
        mlops_svc  = _get_mlops_service(env_root)
        dataset    = _require_dataset(mlops_svc, tenant_id, env_id, body)
        result     = mlops_svc.feature_target(
            dataset,
            body.get("target_column") or "",
            int(body.get("sample_rows") or 5000),
        )
        return jsonify({"success": True, "data": result}), 200
    except ValueError as ve:
        return jsonify({"success": False, "error": str(ve), "error_code": "NOT_FOUND"}), 404
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


@mlops_workbench_bp.route("/eda/leakage-checks", methods=["POST"])
def mlops_leakage_checks():
    try:
        body = request.get_json(silent=True) or {}
        tenant_id, env_id = _get_env_ids()
        env_root   = _resolve_env_path(env_id, tenant_id)
        mlops_svc  = _get_mlops_service(env_root)
        dataset    = _require_dataset(mlops_svc, tenant_id, env_id, body)
        result     = mlops_svc.leakage_checks(
            dataset,
            body.get("target_column") or "",
            int(body.get("sample_rows") or 5000),
            float(body.get("corr_threshold") or 0.85),
            float(body.get("unique_threshold") or 0.95),
        )
        return jsonify({"success": True, "data": result}), 200
    except ValueError as ve:
        return jsonify({"success": False, "error": str(ve), "error_code": "NOT_FOUND"}), 404
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


@mlops_workbench_bp.route("/eda/pairplot", methods=["POST"])
def mlops_pairplot():
    try:
        body = request.get_json(silent=True) or {}
        tenant_id, env_id = _get_env_ids()
        env_root   = _resolve_env_path(env_id, tenant_id)
        mlops_svc  = _get_mlops_service(env_root)
        dataset    = _require_dataset(mlops_svc, tenant_id, env_id, body)
        result     = mlops_svc.pairplot(
            dataset,
            body.get("columns"),
            int(body.get("sample_rows") or 2000),
            int(body.get("bins") or 12),
        )
        return jsonify({"success": True, "data": result}), 200
    except ValueError as ve:
        return jsonify({"success": False, "error": str(ve), "error_code": "NOT_FOUND"}), 404
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


@mlops_workbench_bp.route("/eda/interaction-heatmap", methods=["POST"])
def mlops_interaction_heatmap():
    try:
        body = request.get_json(silent=True) or {}
        tenant_id, env_id = _get_env_ids()
        env_root   = _resolve_env_path(env_id, tenant_id)
        mlops_svc  = _get_mlops_service(env_root)
        dataset    = _require_dataset(mlops_svc, tenant_id, env_id, body)
        result     = mlops_svc.interaction_heatmap(
            dataset,
            body.get("columns"),
            int(body.get("sample_rows") or 4000),
        )
        return jsonify({"success": True, "data": result}), 200
    except ValueError as ve:
        return jsonify({"success": False, "error": str(ve), "error_code": "NOT_FOUND"}), 404
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


@mlops_workbench_bp.route("/eda/bivariate-categorical", methods=["POST"])
def mlops_bivariate_categorical():
    try:
        body = request.get_json(silent=True) or {}
        tenant_id, env_id = _get_env_ids()
        env_root   = _resolve_env_path(env_id, tenant_id)
        mlops_svc  = _get_mlops_service(env_root)
        dataset    = _require_dataset(mlops_svc, tenant_id, env_id, body)
        result     = mlops_svc.bivariate_categorical(
            dataset,
            body.get("column_x") or "",
            body.get("column_y") or "",
            int(body.get("sample_rows") or 4000),
            int(body.get("limit") or 15),
        )
        return jsonify({"success": True, "data": result}), 200
    except ValueError as ve:
        return jsonify({"success": False, "error": str(ve), "error_code": "NOT_FOUND"}), 404
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


@mlops_workbench_bp.route("/eda/segment-target", methods=["POST"])
def mlops_segment_target():
    """
    Compute TP-rate-by-segment charts: for each requested column,
    groups the dataset by that column's values and returns the mean
    of the binary target column per group.

    Body: { dataset_id, target_column, columns: [...], sample_rows, max_categories }
    Returns: { segments: { col: [ {label, tp_rate, count} ] } }
    """
    try:
        body = request.get_json(silent=True) or {}
        tenant_id, env_id = _get_env_ids()
        env_root   = _resolve_env_path(env_id, tenant_id)
        mlops_svc  = _get_mlops_service(env_root)
        dataset    = _require_dataset(mlops_svc, tenant_id, env_id, body)
        result     = mlops_svc.segment_target(
            dataset,
            body.get("target_column") or "",
            body.get("columns") or [],
            int(body.get("sample_rows") or 10000),
            int(body.get("max_categories") or 25),
        )
        return jsonify({"success": True, "data": result}), 200
    except ValueError as ve:
        return jsonify({"success": False, "error": str(ve), "error_code": "NOT_FOUND"}), 404
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


# â”€â”€â”€ Preprocessing â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

@mlops_workbench_bp.route("/preprocess/plan", methods=["POST"])
def mlops_preprocess_plan():
    try:
        body = request.get_json(silent=True) or {}
        tenant_id, env_id = _get_env_ids()
        env_root   = _resolve_env_path(env_id, tenant_id)
        mlops_svc  = _get_mlops_service(env_root)
        dataset    = _require_dataset(mlops_svc, tenant_id, env_id, body)
        result     = mlops_svc.preprocess_plan(dataset, int(body.get("sample_rows") or 5000))
        return jsonify({"success": True, "data": result}), 200
    except ValueError as ve:
        return jsonify({"success": False, "error": str(ve), "error_code": "NOT_FOUND"}), 404
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


@mlops_workbench_bp.route("/preprocess/preview", methods=["POST"])
def mlops_preprocess_preview():
    try:
        body = request.get_json(silent=True) or {}
        tenant_id, env_id = _get_env_ids()
        env_root   = _resolve_env_path(env_id, tenant_id)
        mlops_svc  = _get_mlops_service(env_root)
        dataset    = _require_dataset(mlops_svc, tenant_id, env_id, body)
        result     = mlops_svc.preprocess_preview(
            dataset,
            body.get("steps") or [],
            int(body.get("sample_rows") or 100),
            target_column=str(body.get("target_column") or "").strip() or None,
        )
        return jsonify({"success": True, "data": result}), 200
    except ValueError as ve:
        return jsonify({"success": False, "error": str(ve), "error_code": "NOT_FOUND"}), 404
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


@mlops_workbench_bp.route("/preprocess/run", methods=["POST"])
def mlops_preprocess_run():
    try:
        body = request.get_json(silent=True) or {}
        tenant_id, env_id = _get_env_ids()
        env_root   = _resolve_env_path(env_id, tenant_id)
        mlops_svc  = _get_mlops_service(env_root)
        dataset    = _require_dataset(mlops_svc, tenant_id, env_id, body)
        output_name = _safe_dataset_type(body.get("output_name") or "preprocessed_dataset")
        result = mlops_svc.preprocess_run(
            tenant_id, env_id, dataset,
            body.get("steps") or [],
            output_name,
            target_column=str(body.get("target_column") or "").strip() or None,
        )
        return jsonify({"success": True, "data": result}), 200
    except ValueError as ve:
        return jsonify({"success": False, "error": str(ve), "error_code": "VALIDATION_ERROR"}), 400
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


@mlops_workbench_bp.route("/preprocess/master-build", methods=["POST"])
def mlops_master_build():
    try:
        body = request.get_json(silent=True) or {}
        tenant_id, env_id = _get_env_ids()
        env_root    = _resolve_env_path(env_id, tenant_id)
        mlops_svc   = _get_mlops_service(env_root)
        dataset_ids = body.get("dataset_ids") or []
        datasets    = [
            mlops_svc.get_dataset(tenant_id, env_id, int(did))
            for did in dataset_ids if did
        ]
        datasets   = [d for d in datasets if d]
        output_name = _safe_dataset_type(body.get("output_name") or "master_dataset")
        options = {
            "join_keys": body.get("join_keys") or body.get("join_steps") or [],
            "base_dataset_type": body.get("base_dataset_type"),
            "str_policy": body.get("str_policy") or "detect",
            "replacement_label_column": body.get("replacement_label_column"),
            "preview_rows": int(body.get("preview_rows") or 40),
            "master_mode": body.get("master_mode") or "auto",
        }
        result      = mlops_svc.build_master_dataset(tenant_id, env_id, datasets, output_name, options)
        return jsonify({"success": True, "data": _json_safe(result)}), 200
    except ValueError as ve:
        return jsonify({"success": False, "error": str(ve), "error_code": "VALIDATION_ERROR"}), 400
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


@mlops_workbench_bp.route("/preprocess/master-preview", methods=["POST"])
def mlops_master_preview():
    try:
        body = request.get_json(silent=True) or {}
        tenant_id, env_id = _get_env_ids()
        env_root    = _resolve_env_path(env_id, tenant_id)
        mlops_svc   = _get_mlops_service(env_root)
        dataset_ids = body.get("dataset_ids") or []
        datasets    = [
            mlops_svc.get_dataset(tenant_id, env_id, int(did))
            for did in dataset_ids if did
        ]
        datasets = [d for d in datasets if d]
        options = {
            "join_keys": body.get("join_keys") or body.get("join_steps") or [],
            "base_dataset_type": body.get("base_dataset_type"),
            "str_policy": body.get("str_policy") or "detect",
            "replacement_label_column": body.get("replacement_label_column"),
            "preview_rows": int(body.get("preview_rows") or 40),
            "master_mode": body.get("master_mode") or "auto",
        }
        result = mlops_svc.preview_master_dataset(tenant_id, env_id, datasets, options)
        return jsonify({"success": True, "data": _json_safe(result)}), 200
    except ValueError as ve:
        return jsonify({"success": False, "error": str(ve), "error_code": "VALIDATION_ERROR"}), 400
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


# â”€â”€â”€ Pipeline â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

@mlops_workbench_bp.route("/pipeline/preview", methods=["POST"])
def mlops_pipeline_preview():
    try:
        body = request.get_json(silent=True) or {}
        tenant_id, env_id = _get_env_ids()
        env_root   = _resolve_env_path(env_id, tenant_id)
        mlops_svc  = _get_mlops_service(env_root)
        dataset    = _require_dataset(mlops_svc, tenant_id, env_id, body)
        result     = mlops_svc.preprocess_preview(
            dataset, body.get("steps") or [], int(body.get("sample_rows") or 100)
        )
        return jsonify({"success": True, "data": result}), 200
    except ValueError as ve:
        return jsonify({"success": False, "error": str(ve), "error_code": "NOT_FOUND"}), 404
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


@mlops_workbench_bp.route("/pipeline/save", methods=["POST"])
def mlops_pipeline_save():
    """
    POST /api/mlops/pipeline/save

    Full pipeline definition save. Accepts both the legacy minimal payload
    { dataset_id, name, steps } and the extended payload that drives the
    Master Dataset screen:

      {
        name, description,
        grain,                     // "transaction" | "alert" | "case"
        anchor_dataset_id,         // ID of the base/anchor table
        dataset_ids,               // [id, id, ...] â€” all tables to include
        joins,                     // [{ left, right, key, join_type, enabled }]
        transforms,                // [{ type, columns, ... }]
        str_config,                // { policy, replacement_label_column }
        schedule,                  // { enabled, frequency, time, day, cron, trigger_on_upload }
        output_name,               // registered dataset name for the output
        created_by_persona,        // "business" | "technical"
        steps                      // legacy flat step list (still accepted)
      }

    Returns { pipeline_id, version, name, status }
    """
    try:
        body = request.get_json(silent=True) or {}
        tenant_id, env_id = _get_env_ids()
        env_root   = _resolve_env_path(env_id, tenant_id)
        mlops_svc  = _get_mlops_service(env_root)

        name       = body.get("name") or "Unnamed Pipeline"
        dataset_id = int(body.get("dataset_id") or 0)
        steps      = body.get("steps") or []

        result = mlops_svc.save_pipeline(
            tenant_id, env_id, dataset_id, name, steps,
            grain=str(body.get("grain") or "transaction"),
            anchor_dataset_id=int(body["anchor_dataset_id"]) if body.get("anchor_dataset_id") else None,
            dataset_ids=[int(d) for d in (body.get("dataset_ids") or []) if d],
            joins=list(body.get("joins") or []),
            transforms=list(body.get("transforms") or []),
            str_config=dict(body.get("str_config") or {}),
            schedule=dict(body.get("schedule") or {}),
            output_name=str(body.get("output_name") or "master_dataset"),
            created_by_persona=str(body.get("created_by_persona") or "technical"),
        )
        return jsonify({"success": True, "data": result}), 200
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


@mlops_workbench_bp.route("/pipeline/<int:pipeline_id>", methods=["GET"])
def mlops_pipeline_get(pipeline_id):
    """GET /api/mlops/pipeline/<id> â€” Load the full pipeline definition."""
    try:
        tenant_id, env_id = _get_env_ids()
        env_root  = _resolve_env_path(env_id, tenant_id)
        mlops_svc = _get_mlops_service(env_root)
        result    = mlops_svc.load_pipeline(tenant_id, env_id, pipeline_id)
        return jsonify({"success": True, "data": result}), 200
    except ValueError as ve:
        return jsonify({"success": False, "error": str(ve), "error_code": "NOT_FOUND"}), 404
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


@mlops_workbench_bp.route("/pipeline/<int:pipeline_id>/screen-state", methods=["POST"])
def mlops_pipeline_screen_state(pipeline_id):
    """
    POST /api/mlops/pipeline/<id>/screen-state

    Lightweight state save for one workbench screen. Used for autosave and
    exact resume without creating a full new pipeline version on each UI move.
    """
    try:
        body = request.get_json(silent=True) or {}
        screen = str(body.get("screen") or "").strip()
        state = body.get("state") or {}
        if not screen:
            return jsonify({
                "success": False,
                "error": "screen is required",
                "error_code": "VALIDATION_ERROR",
            }), 400
        if not isinstance(state, dict):
            return jsonify({
                "success": False,
                "error": "state must be an object",
                "error_code": "VALIDATION_ERROR",
            }), 400

        tenant_id, env_id = _get_env_ids()
        env_root = _resolve_env_path(env_id, tenant_id)
        mlops_svc = _get_mlops_service(env_root)
        result = mlops_svc.save_pipeline_screen_state(tenant_id, env_id, int(pipeline_id), screen, state)
        return jsonify({"success": True, "data": result}), 200
    except ValueError as ve:
        return jsonify({"success": False, "error": str(ve), "error_code": "NOT_FOUND"}), 404
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


@mlops_workbench_bp.route("/pipeline/<int:pipeline_id>", methods=["DELETE"])
def mlops_pipeline_delete(pipeline_id):
    """
    DELETE /api/mlops/pipeline/<id>?delete_artifacts=1&delete_files=1

    Deletes a saved pipeline. By default also deletes pipeline-generated artefacts.
    """
    try:
        tenant_id, env_id = _get_env_ids()
        env_root = _resolve_env_path(env_id, tenant_id)
        mlops_svc = _get_mlops_service(env_root)

        delete_artifacts_raw = str(request.args.get("delete_artifacts", "1")).strip().lower()
        delete_files_raw = str(request.args.get("delete_files", "1")).strip().lower()
        delete_artifacts = delete_artifacts_raw not in {"0", "false", "no", "off"}
        delete_files = delete_files_raw not in {"0", "false", "no", "off"}

        result = mlops_svc.delete_pipeline(
            tenant_id,
            env_id,
            int(pipeline_id),
            delete_artifacts=delete_artifacts,
            delete_files=delete_files,
        )
        return jsonify({"success": True, "data": result}), 200
    except ValueError as ve:
        return jsonify({"success": False, "error": str(ve), "error_code": "NOT_FOUND"}), 404
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


@mlops_workbench_bp.route("/pipeline/<int:pipeline_id>/run", methods=["POST"])
def mlops_pipeline_run(pipeline_id):
    """
    POST /api/mlops/pipeline/<id>/run

    Trigger an async pipeline build. Returns immediately with a run_id
    that the frontend polls via GET /pipeline/<id>/status?run_id=<run_id>.

    Returns HTTP 202 { run_id }
    """
    try:
        tenant_id, env_id = _get_env_ids()
        env_root  = _resolve_env_path(env_id, tenant_id)
        mlops_svc = _get_mlops_service(env_root)
        run_id    = mlops_svc.run_pipeline_async(tenant_id, env_id, pipeline_id)
        return jsonify({"success": True, "run_id": run_id}), 202
    except ValueError as ve:
        return jsonify({"success": False, "error": str(ve), "error_code": "NOT_FOUND"}), 404
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


@mlops_workbench_bp.route("/pipeline/<int:pipeline_id>/status", methods=["GET"])
def mlops_pipeline_status(pipeline_id):
    """
    GET /api/mlops/pipeline/<id>/status?run_id=<run_id>

    If run_id is supplied, returns that specific run record (status, log, error).
    If not supplied, returns the pipeline header status from the registry.
    """
    try:
        tenant_id, env_id = _get_env_ids()
        env_root   = _resolve_env_path(env_id, tenant_id)
        mlops_svc  = _get_mlops_service(env_root)
        run_id     = request.args.get("run_id")

        if run_id:
            result = mlops_svc.get_pipeline_run_status(run_id)
        else:
            pipeline = mlops_svc.load_pipeline(tenant_id, env_id, pipeline_id)
            result = {
                "pipeline_id": pipeline_id,
                "status": pipeline.get("status") or "draft",
                "version": pipeline.get("version") or 1,
                "last_run_at": pipeline.get("last_run_at"),
                "output_dataset_id": pipeline.get("output_dataset_id"),
            }
        return jsonify({"success": True, "data": result}), 200
    except ValueError as ve:
        return jsonify({"success": False, "error": str(ve), "error_code": "NOT_FOUND"}), 404
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


@mlops_workbench_bp.route("/pipeline/<int:pipeline_id>/versions", methods=["GET"])
def mlops_pipeline_versions(pipeline_id):
    """GET /api/mlops/pipeline/<id>/versions â€” All saved version snapshots."""
    try:
        tenant_id, env_id = _get_env_ids()
        env_root  = _resolve_env_path(env_id, tenant_id)
        mlops_svc = _get_mlops_service(env_root)
        versions  = mlops_svc.list_pipeline_versions(tenant_id, env_id, pipeline_id)
        return jsonify({"success": True, "data": versions}), 200
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


@mlops_workbench_bp.route("/pipeline/<int:pipeline_id>/schedule", methods=["POST"])
def mlops_pipeline_schedule(pipeline_id):
    """
    POST /api/mlops/pipeline/<id>/schedule

    Body: { enabled, frequency, time, day, cron, trigger_on_upload }
    Persists schedule settings on the pipeline record.
    """
    try:
        body      = request.get_json(silent=True) or {}
        tenant_id, env_id = _get_env_ids()
        env_root  = _resolve_env_path(env_id, tenant_id)
        mlops_svc = _get_mlops_service(env_root)
        result    = mlops_svc.schedule_pipeline(tenant_id, env_id, pipeline_id, body)
        return jsonify({"success": True, "data": result}), 200
    except ValueError as ve:
        return jsonify({"success": False, "error": str(ve), "error_code": "NOT_FOUND"}), 404
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500




@mlops_workbench_bp.route("/pipeline/list", methods=["GET"])
def mlops_pipeline_list():
    try:
        tenant_id, env_id = _get_env_ids()
        dataset_id = request.args.get("dataset_id")
        env_root   = _resolve_env_path(env_id, tenant_id)
        mlops_svc  = _get_mlops_service(env_root)
        result     = mlops_svc.list_pipelines(
            tenant_id, env_id, int(dataset_id) if dataset_id else None
        )
        return jsonify({"success": True, "data": result}), 200
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


# â”€â”€â”€ Snapshots & Jobs â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

# Stage 6-9: Model training, evaluation, threshold tuning, deployment
@mlops_workbench_bp.route("/model/train", methods=["POST"])
def mlops_model_train():
    try:
        body = request.get_json(silent=True) or {}
        dataset_id = int(body.get("dataset_id") or 0)
        target_column = str(body.get("target_column") or "").strip()
        if not dataset_id or not target_column:
            return jsonify({
                "success": False,
                "error": "dataset_id and target_column are required",
                "error_code": "VALIDATION_ERROR",
            }), 400

        test_size = float(body.get("test_size") or 0.2)
        random_state = int(body.get("random_state") or 42)
        tenant_id, env_id = _get_env_ids()
        env_root = _resolve_env_path(env_id, tenant_id)
        mlops_svc = _get_mlops_service(env_root)
        dataset = mlops_svc.get_dataset(tenant_id, env_id, dataset_id)
        result = mlops_svc.train_false_positive_model(
            tenant_id=tenant_id,
            env_id=env_id,
            dataset=dataset,
            target_column=target_column,
            test_size=test_size,
            random_state=random_state,
        )
        return jsonify({"success": True, "data": result}), 200
    except ValueError as ve:
        return jsonify({"success": False, "error": str(ve), "error_code": "VALIDATION_ERROR"}), 400
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


@mlops_workbench_bp.route("/model/evaluate", methods=["POST"])
def mlops_model_evaluate():
    try:
        body = request.get_json(silent=True) or {}
        run_id = str(body.get("run_id") or "").strip()
        if not run_id:
            return jsonify({"success": False, "error": "run_id is required", "error_code": "VALIDATION_ERROR"}), 400
        threshold = float(body.get("threshold") or 0.40)
        tenant_id, env_id = _get_env_ids()
        env_root = _resolve_env_path(env_id, tenant_id)
        mlops_svc = _get_mlops_service(env_root)
        result = mlops_svc.evaluate_model_run(run_id=run_id, threshold=threshold)
        return jsonify({"success": True, "data": result}), 200
    except ValueError as ve:
        return jsonify({"success": False, "error": str(ve), "error_code": "VALIDATION_ERROR"}), 400
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


@mlops_workbench_bp.route("/model/threshold-tune", methods=["POST"])
def mlops_model_threshold_tune():
    try:
        body = request.get_json(silent=True) or {}
        run_id = str(body.get("run_id") or "").strip()
        if not run_id:
            return jsonify({"success": False, "error": "run_id is required", "error_code": "VALIDATION_ERROR"}), 400
        max_event_loss_pct = float(body.get("max_event_loss_pct") or 5.0)
        tenant_id, env_id = _get_env_ids()
        env_root = _resolve_env_path(env_id, tenant_id)
        mlops_svc = _get_mlops_service(env_root)
        result = mlops_svc.tune_model_threshold(
            run_id=run_id,
            max_event_loss_pct=max_event_loss_pct,
        )
        return jsonify({"success": True, "data": result}), 200
    except ValueError as ve:
        return jsonify({"success": False, "error": str(ve), "error_code": "VALIDATION_ERROR"}), 400
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


@mlops_workbench_bp.route("/model/deploy", methods=["POST"])
def mlops_model_deploy():
    try:
        body = request.get_json(silent=True) or {}
        run_id = str(body.get("run_id") or "").strip()
        if not run_id:
            return jsonify({"success": False, "error": "run_id is required", "error_code": "VALIDATION_ERROR"}), 400
        threshold = body.get("threshold")
        deployment_name = body.get("deployment_name")
        tenant_id, env_id = _get_env_ids()
        env_root = _resolve_env_path(env_id, tenant_id)
        mlops_svc = _get_mlops_service(env_root)
        result = mlops_svc.deploy_model_run(
            tenant_id=tenant_id,
            env_id=env_id,
            run_id=run_id,
            threshold=float(threshold) if threshold is not None else None,
            deployment_name=deployment_name,
        )
        return jsonify({"success": True, "data": result}), 200
    except ValueError as ve:
        return jsonify({"success": False, "error": str(ve), "error_code": "VALIDATION_ERROR"}), 400
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


@mlops_workbench_bp.route("/model/runs", methods=["GET"])
def mlops_model_runs():
    try:
        tenant_id, env_id = _get_env_ids()
        dataset_id = request.args.get("dataset_id")
        env_root = _resolve_env_path(env_id, tenant_id)
        mlops_svc = _get_mlops_service(env_root)
        result = mlops_svc.list_model_runs(
            tenant_id=tenant_id,
            env_id=env_id,
            dataset_id=int(dataset_id) if dataset_id else None,
        )
        return jsonify({"success": True, "data": result}), 200
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


@mlops_workbench_bp.route("/model/runs/<run_id>", methods=["GET"])
def mlops_model_run_detail(run_id):
    try:
        tenant_id, env_id = _get_env_ids()
        env_root = _resolve_env_path(env_id, tenant_id)
        mlops_svc = _get_mlops_service(env_root)
        run = mlops_svc.get_model_run(str(run_id))
        if run.get("tenant_id") != tenant_id or run.get("env_id") != env_id:
            return jsonify({"success": False, "error": "Model run not found", "error_code": "NOT_FOUND"}), 404
        return jsonify({"success": True, "data": run}), 200
    except ValueError:
        return jsonify({"success": False, "error": "Model run not found", "error_code": "NOT_FOUND"}), 404
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


@mlops_workbench_bp.route("/snapshots/create", methods=["POST"])
def mlops_create_snapshot():
    try:
        body = request.get_json(silent=True) or {}
        tenant_id, env_id = _get_env_ids()
        env_root   = _resolve_env_path(env_id, tenant_id)
        mlops_svc  = _get_mlops_service(env_root)
        result     = mlops_svc.create_snapshot(
            tenant_id, env_id,
            body.get("name") or "Snapshot",
            body.get("dataset_id"),
            body,
        )
        return jsonify({"success": True, "data": result}), 200
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


@mlops_workbench_bp.route("/snapshots", methods=["GET"])
def mlops_list_snapshots():
    try:
        tenant_id, env_id = _get_env_ids()
        env_root   = _resolve_env_path(env_id, tenant_id)
        mlops_svc  = _get_mlops_service(env_root)
        result     = mlops_svc.list_snapshots(tenant_id, env_id)
        return jsonify({"success": True, "data": result}), 200
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500


@mlops_workbench_bp.route("/jobs/<job_id>", methods=["GET"])
def mlops_job_status(job_id):
    try:
        tenant_id, env_id = _get_env_ids()
        env_root   = _resolve_env_path(env_id, tenant_id)
        mlops_svc  = _get_mlops_service(env_root)
        result     = mlops_svc.get_job_status(job_id)
        if not result:
            return jsonify({"success": False, "error": "Job not found.", "error_code": "NOT_FOUND"}), 404
        return jsonify({"success": True, "data": result}), 200
    except Exception as exc:
        return jsonify({"success": False, "error": str(exc), "error_code": "SERVER_ERROR"}), 500



