// frontend/src/tools/calibration/components/DecisionRationalePanel.jsx
// PwC Professional Design

import React from 'react';
import {
  Card, CardContent, Box, Typography, TextField, 
  Alert, Stack, Chip
} from '@mui/material';
import { AutoAwesome, Edit, Info } from '@mui/icons-material';

const PWC_COLORS = {
  orange: '#D04A02',
  darkGray: '#2C2C2C',
  mediumGray: '#53565A',
  lightGray: '#E6E6E6',
  white: '#FFFFFF',
  infoLight: '#F5F9FF'
};

const DecisionRationalePanel = ({ 
  rationale, 
  onRationaleChange, 
  metadata,
  isAutoGenerated = true 
}) => {
  return (
    <Card 
      variant="outlined"
      sx={{ 
        border: `1px solid ${PWC_COLORS.lightGray}`,
        boxShadow: 'none',
        mb: 2
      }}
    >
      <CardContent sx={{ px: 3, py: 3 }}>
        <Stack direction="row" justifyContent="space-between" alignItems="center" mb={2}>
          <Typography 
            variant="subtitle2" 
            fontWeight={600}
            sx={{ 
              color: PWC_COLORS.darkGray,
              fontSize: '0.938rem'
            }}
          >
            Decision Rationale
          </Typography>
          {isAutoGenerated && (
            <Chip 
              icon={<AutoAwesome sx={{ fontSize: '0.875rem' }} />} 
              label="Auto-generated" 
              size="small" 
              sx={{
                bgcolor: PWC_COLORS.infoLight,
                color: PWC_COLORS.orange,
                border: `1px solid ${PWC_COLORS.orange}`,
                fontWeight: 500,
                fontSize: '0.75rem',
                height: 24,
                '& .MuiChip-icon': {
                  color: PWC_COLORS.orange
                }
              }}
            />
          )}
        </Stack>
        
        {/* Context Bar */}
        {metadata && (
          <Alert 
            severity="info" 
            icon={<Info sx={{ color: PWC_COLORS.orange, fontSize: '1rem' }} />}
            sx={{ 
              mb: 2.5, 
              py: 0.75,
              border: `1px solid ${PWC_COLORS.lightGray}`,
              '& .MuiAlert-message': {
                color: PWC_COLORS.darkGray
              }
            }}
          >
            <Typography 
              variant="caption"
              sx={{ fontSize: '0.813rem' }}
            >
              <strong>Context:</strong>{' '}
              {metadata.aggregation || 'N/A'} | {' '}
              {metadata.alert_grain || 'N/A'} level | {' '}
              {metadata.lookback_days || 'N/A'} days lookback
            </Typography>
          </Alert>
        )}
        
        {/* Editable Text Field */}
        <TextField
          multiline
          rows={6}
          fullWidth
          placeholder="Explain why this threshold was chosen. The auto-generated text above provides a starting point. Feel free to edit or add context specific to your use case..."
          value={rationale}
          onChange={(e) => onRationaleChange && onRationaleChange(e.target.value)}
          variant="outlined"
          size="small"
          InputProps={{
            startAdornment: (
              <Box sx={{ pr: 1, pt: 1 }}>
                <Edit fontSize="small" sx={{ color: PWC_COLORS.mediumGray }} />
              </Box>
            )
          }}
          sx={{
            '& .MuiOutlinedInput-root': {
              bgcolor: PWC_COLORS.white,
              fontFamily: '"Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
              fontSize: '0.875rem',
              color: PWC_COLORS.darkGray,
              lineHeight: 1.6,
              '& fieldset': {
                borderColor: PWC_COLORS.lightGray
              },
              '&:hover fieldset': {
                borderColor: PWC_COLORS.orange
              },
              '&.Mui-focused fieldset': {
                borderColor: PWC_COLORS.orange,
                borderWidth: 1
              }
            }
          }}
        />
        
        {/* Character Count */}
        <Box sx={{ mt: 1.5, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <Typography 
            variant="caption" 
            sx={{ 
              color: PWC_COLORS.mediumGray,
              fontSize: '0.75rem'
            }}
          >
            {rationale?.length || 0} characters
          </Typography>
          <Typography 
            variant="caption" 
            sx={{ 
              color: PWC_COLORS.mediumGray,
              fontSize: '0.75rem'
            }}
          >
            This text will be saved with the calibration for audit purposes
          </Typography>
        </Box>
        
        {/* Help Text */}
        <Box 
          sx={{ 
            mt: 2.5, 
            p: 2, 
            bgcolor: '#FAFAFA', 
            borderRadius: 1, 
            border: `1px solid ${PWC_COLORS.lightGray}`
          }}
        >
          <Typography 
            variant="caption" 
            sx={{ 
              color: PWC_COLORS.darkGray,
              fontSize: '0.813rem',
              fontWeight: 600,
              display: 'block',
              mb: 1
            }}
          >
            Good rationales include:
          </Typography>
          <Box component="ul" sx={{ mt: 0.5, mb: 0, pl: 2.5 }}>
            <Typography 
              component="li" 
              variant="caption" 
              sx={{ 
                color: PWC_COLORS.mediumGray,
                fontSize: '0.813rem',
                lineHeight: 1.8
              }}
            >
              Why this percentile was chosen over others
            </Typography>
            <Typography 
              component="li" 
              variant="caption" 
              sx={{ 
                color: PWC_COLORS.mediumGray,
                fontSize: '0.813rem',
                lineHeight: 1.8
              }}
            >
              How it aligns with risk appetite and operational capacity
            </Typography>
            <Typography 
              component="li" 
              variant="caption" 
              sx={{ 
                color: PWC_COLORS.mediumGray,
                fontSize: '0.813rem',
                lineHeight: 1.8
              }}
            >
              Any specific considerations (seasonality, regulatory requirements, etc.)
            </Typography>
            <Typography 
              component="li" 
              variant="caption" 
              sx={{ 
                color: PWC_COLORS.mediumGray,
                fontSize: '0.813rem',
                lineHeight: 1.8
              }}
            >
              Expected review frequency
            </Typography>
          </Box>
        </Box>
      </CardContent>
    </Card>
  );
};

export default DecisionRationalePanel;