export const FCC_THEME = {
  accent: '#D04A02',
  accentHover: '#B03F00',
  accentSoft: '#F8F6F3',
  accentSoftStrong: '#F2EEEA',
  accentBorder: '#D8C7BA',
  canvas: '#F3F4F5',
  page: '#F5F6F7',
  panel: '#FFFFFF',
  panelAlt: '#F8F9FA',
  panelMuted: '#F2F3F4',
  chrome: '#2C2723',
  chromeBorder: '#433A33',
  rail: '#332C26',
  railBorder: '#494039',
  railHover: 'rgba(255,255,255,0.05)',
  railActive: 'rgba(208,74,2,0.10)',
  text: '#1E2329',
  textStrong: '#171B20',
  textMuted: '#46515C',
  textSoft: '#5C6875',
  textOnDark: '#F7F6F4',
  textMutedOnDark: '#D2CAC2',
  border: '#D9DEE5',
  borderStrong: '#C7CED7',
  success: '#2E7D32',
  successBg: '#F7F9F7',
  successBorder: '#CCD8CE',
  warning: '#8A5A00',
  warningBg: '#F8F6F2',
  warningBorder: '#DDD6C8',
  error: '#B42318',
  errorBg: '#F9F4F3',
  errorBorder: '#E3CFCC',
  info: '#495867',
  infoBg: '#F5F7F9',
  infoBorder: '#DCE3EA',
  shadowSm: '0 1px 2px rgba(22, 18, 14, 0.06)',
  shadowMd: '0 12px 26px rgba(22, 18, 14, 0.08)',
  radiusSm: 0,
  radiusMd: 2,
  radiusLg: 4,
};

export const FCC_STATUS_TONES = {
  pending: {
    bg: FCC_THEME.panelAlt,
    bd: FCC_THEME.border,
    fg: FCC_THEME.textMuted,
    label: 'Pending',
  },
  running: {
    bg: FCC_THEME.accentSoft,
    bd: FCC_THEME.accentBorder,
    fg: FCC_THEME.accent,
    label: 'Running',
  },
  done: {
    bg: FCC_THEME.successBg,
    bd: FCC_THEME.successBorder,
    fg: FCC_THEME.success,
    label: 'Done',
  },
  error: {
    bg: FCC_THEME.errorBg,
    bd: FCC_THEME.errorBorder,
    fg: FCC_THEME.error,
    label: 'Error',
  },
  skipped: {
    bg: FCC_THEME.panelMuted,
    bd: FCC_THEME.border,
    fg: FCC_THEME.textSoft,
    label: 'Skipped',
  },
};
